import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../app/components/Navbar"
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from '../app/context/AuthContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
     
      <body className={inter.className}>
      <Navbar />
        {children}</body>
    </html>
    </AuthProvider>
  );
}
